variable "location" {
  type = string
  default = "UK South"
}

variable "managed_image_name" {
  type = string
  default = "IvanPackerImage-UKsouth"
}

variable "managed_image_resource_group_name" {
  type = string
  default = "IvanPackerResourceGroup"
}

variable "vm_size" {
  type = string
  default = "Standard_DS2_v2"
}

source "azure-arm" "autogenerated_1" {
  azure_tags = {
    dept = "Engineering"
    task = "Image deployment"
  }
  client_id                         = "***"
  client_secret                     = "***"
  subscription_id                   = "***"
  tenant_id                         = "***"
  
  image_offer                       = "0001-com-ubuntu-server-jammy"
  image_publisher                   = "canonical"
  image_sku                         = "22_04-lts"
  location                          = var.location
  managed_image_name                = var.managed_image_name
  managed_image_resource_group_name = var.managed_image_resource_group_name
  os_type                           = "Linux"
  vm_size                           = var.vm_size
}

build {
  sources = ["source.azure-arm.autogenerated_1"]

  provisioner "shell" {
    execute_command = "chmod +x {{ .Path }}; {{ .Vars }} sudo -E sh '{{ .Path }}'"
    #inline          = ["apt-get update", "apt-get upgrade -y", "apt-get -y install nginx", "/usr/sbin/waagent -force -deprovision+user && export HISTSIZE=0 && sync"]
    
    inline          = ["apt update", "apt upgrade -y", "apt install -y software-properties-common gnupg2 curl", "curl -L https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh | bash", "apt install -y jq" ]
    inline_shebang  = "/bin/sh -x"
  }

}
